update

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -1,9 +1,17 @@
 #!/bin/bash
 
 echo "@@@@@@@@@@@@@@@@@@@@@   Making pre-invocation changes...  @@@@@@@@@@@@@@@@@@@@@@@@@@"
-cp -Rf /tmp/src/ ./
+rc=$?
+if [ $rc -eq 0 ]; then
+
+echo "@@@@@@@@@@@@@@@@@@@@@   Making post-invocation changes...  @@@@@@@@@@@@@@@@@@@@@@@@@@"
 
 DATE=`date "+%b %d, %Y @ %H:%M %p"`
 
-echo "---> Creating info page"
+echo "---> Update index page"
 echo "Page built on $DATE" >> ./index.js
+
+else
+echo "Error: assemble failed!"
+fi
+exit $rc
